### ISSUE TITLE
package issue possibly

### ISSUE THREAD

**Issue by mujeebishaque** [leoyn/social-scraper#1]
>First:

ModuleNotFoundError: No module named 'social_scraper.platforms'

>second:

`PlatformFactory.create(PlatformEnumeration.TWITTER).search(query).saveAsCSV("test.csv")`

After this line, I get the following error:
Why is `--json` an unrecognized argument?

**Comment by leoyn** [comment]
1. Did you install it using pip?
2. Try to uninstall `snscrape` and `social_scraper` and reinstall `social_scraper`.
```bash
pip3 uninstall snscrape social_scraper && pip3 install git+https://github.com/leoyn/social-scraper.git
```
This is due to the current bugs in snscrape from release v0.3.4. Please use the from git master branch. `social_scraper` automatically installs `snscrape`for you.

**Comment by mujeebishaque** [comment]
>ERROR: Package 'snscrape' requires a different Python: 3.7.4 not in '~=3.8'

I guess it's time for me to update python from 3.7 to 3.8.

**Comment by mujeebishaque** [comment]
Thank You for the help. My bad. I missed the requirements part. It requires Python 3.8;
